repos:
  - repo: local
    hooks:
      - id: clang-format-tidy
        name: Clang-Format Tidy
        entry: ./tools/code_check_wrapper.sh
        language: script
        files: \.(cpp|h|hpp)$
        pass_filenames: false

  - repo: local
    hooks:
      - id: git-lfs
        name: Git LFS
        entry: git lfs pre-push "$@"
        language: system
        stages: [push]
