file(GLOB_RECURSE  VENDORS_DEFAULT_CONFIGS "${VENDORS_DEFAULT_CONFIGS_DIR}/*.json")

if(VENDORS_DEFAULT_EXCLUDE_REGEX)
  list(FILTER VENDORS_DEFAULT_CONFIGS EXCLUDE REGEX "${VENDORS_DEFAULT_EXCLUDE_REGEX}")
endif()

file(ARCHIVE_CREATE
  OUTPUT "${VENDORS_DEFAULT_ZIP}"
  PATHS ${VENDORS_DEFAULT_CONFIGS}
  FORMAT zip
)